sudo: required
dist: trusty
language: rust

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
      - sourceline: 'deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main'
      - sourceline: 'deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main'
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libsodium-dev

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH &&
      export LIBRARY_PATH=$HOME/lib &&
      export LD_LIBRARY_PATH=$HOME/lib &&
      export PKG_CONFIG_PATH=$HOME/lib/pkgconfig &&

      cd /tmp

      curl -sSOL https://github.com/zeromq/libzmq/releases/download/v4.2.0/zeromq-4.2.0.tar.gz
      tar zxf zeromq-4.2.0.tar.gz
      cd zeromq-4.2.0
      ./autogen.sh
      ./configure --prefix=$HOME --with-libsodium
      make && make install
      cd ..

      curl -sSOL https://github.com/zeromq/czmq/releases/download/v4.0.1/czmq-4.0.1.tar.gz
      tar zxf czmq-4.0.1.tar.gz
      cd czmq-4.0.1
      ./configure --prefix=$HOME --silent
      make && make install
      cd $TRAVIS_BUILD_DIR

script:
  - travis-cargo build
  - travis-cargo test
  - travis-cargo bench

after_success:
  - travis-cargo coveralls --no-sudo --verify --exclude-pattern="/tmp/,/usr/"

env:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
